Feat/gik 119
Project-Rigel/business-app pull request #72
Opened 2020-09-16 22:15 UTC by agascocompte

## JIRA ISSUE - Animación de carga en la aplicación del business

## Objetivo de la PR

Componente de carga: Spinner + backdrop ( div de toda la pantalla para parar los clicks del usuario). Idealmente se debe poder llamar con un servicio.

## Como probar

Paso 1 Añadir un producto y comprobar la visualización y funcionalidad del loader.
Paso 2 Añadir un cliente y comprobar la visualización y funcionalidad del loader.
Paso 3 Añadir una agenda y comprobar la visualización  y funcionalidad del loader.

## Comentarios adicionales y requerimientos para el revisor.

Prueba funcional, revisión de código.

2020-09-16 22:16 UTC, agascocompte commented
He borrado la implementación del loader al añadir una cita ya que corresponde a las siguientes historias de ususario.

2020-09-17 09:16 UTC, EduardoSimon approved these changes

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/agenda/add-agenda/add-agenda.page.ts
>    async createAgenda() {
Ojo, cuando hay error no va al primer callback del observable, sino al segundo (al de error).
 Podria quedarse infinitamente cargando si algo va mal.

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/customers/add-customer/add-customer.page.ts
> +          this.loader.hideLoader();
no uses then, para algo esta el Await the ES6. [https://medium.com/better-programming/should-i-use-promises-or-async-await-126ab5c98789#:~:text=await%20is%20always%20for%20a,executed%20when%20the%20promise%20resolves.](url). 
Con los then acaba habiendo callback hell, es mas complicado seguir el flujo. Si quieres capturar el error lo metes en un try catch.  Ejemplo: [https://basarat.gitbook.io/typescript/type-system/exceptions](url)

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/login/login.page.ts
> +        this.loader.hideLoader();
lo mismo aqui con el then. Aqui justo no es necesario, porque ya usas el await. La llamada asincrona se esperará en la linea 43 hasta que acabe, y no pasará a la siguiente hasta que no acabe, o bien error o success.

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/login/login.page.ts
>          }
Y esto habria que meterlo en try catch

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/login/login.page.ts
> +    this.loader.showLoader();
Lo mismo aqui lo de los then

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/products/add-product/add-product.component.ts
> +      await this.productService
lo mismo

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/services/appointments.service.ts
>          console.log(a);
fuera el console log

2020-09-17 09:16 UTC, EduardoSimon commented on src/app/services/loader.service.ts
> +    this.loadingController
lo mismo con el then

2020-09-17 09:19 UTC, EduardoSimon requested changes
Hay que cambiar el tema de los then en las promesas

2020-09-17 11:39 UTC, agascocompte commented
Bloqueda hasta que @EduardoSimon  refactorice el login.

2020-09-21 17:19 UTC, EduardoSimon approved these changes

2020-09-21 17:20 UTC, merged