chore: refactored alerts
Project-Rigel/business-app pull request #78
Opened 2020-09-22 16:49 UTC by agascocompte

## JIRA ISSUE - Refactorizar las alertas de la app de business

## Objetivo de la PR

Crear un servicio para lanzar las alertas creadas actualmente.

## Comentarios adicionales y requerimientos para el revisor.

Revision de código.

2020-09-22 16:51 UTC, agascocompte commented
Fíjate sobretodo en el método async presentOkCancelAlert(header: string, message: string). He usado un subject para manejar el handler del botón 'OK'.

2020-09-22 17:58 UTC, EduardoSimon requested changes
Cambiar la interfaz del metodo con observable

2020-09-22 17:58 UTC, EduardoSimon commented on src/app/agenda/agenda-details/agenda-details.page.ts
> +  ionViewDidLeave() {
La desuscripción es mejor en el OnDestroy, porque el IonViewDidLeave puede ejecutarse y que el componente no se destruya.

2020-09-22 17:58 UTC, EduardoSimon commented on src/app/services/alert.service.ts
> +  static AppointmentMustBeConfirmed: Subject<any> = new Subject<any>();
Me gusta lo del subject, pero es mala práctica dejarlos públicos, ya que desde cualquier punto de la app podrian lanzar un valor nuevo. Por ello es mejor dejarlo privado y exponer un observable publico.

2020-09-22 17:58 UTC, EduardoSimon commented on src/app/services/alert.service.ts
> +  static AppointmentMustBeConfirmed: Subject<any> = new Subject<any>();
El hecho de que sea estatico es un problema, porque que pasa si tenemos varios alerts anidados uno encima de otro, o varios en cola?
Creo que lo ideal seria que el PROPIO metodo te devolviera un observable y que en le observable te diera un valor de cancelar o de ok

osea algo del estilo 

await presentOkCanceAlert("Header","Message").susbscribe(result => console.log(result));

2020-09-23 17:56 UTC, EduardoSimon approved these changes

2020-09-23 17:56 UTC, merged